### ISSUE TITLE
PHAsset 공부하기

### ISSUE THREAD

**Issue by kjoonk** [codesquad-memeber-2020/photos-2#2]
관련 클래스 학습
### 키워드
- PHAsset
- PHCachingImageManager
- PHPhotoLibrary

**Comment by kjoonk** [comment]
@delmaSong 가 찾은 링크입니다: [[iOS] Photos Framework를 알아보자. (간단히) :: 고무망치의 Dev N Life](https://rhammer.tistory.com/229)

**Comment by delmaSong** [comment]
PhotoKit에 관해 간략히 정리
https://prod.velog.io/@delmasong/PhotoKit에-대해-알아봅시다
