### ISSUE TITLE
PHPhotoLibrary 클래스에 사진보관함이 변경되는지 여부를 옵저버로 등록

### ISSUE THREAD

**Issue by delmaSong** [codesquad-memeber-2020/photos-2#5]
PHPhotoLibrary 클래스에 사진보관함이 변경되는지 여부를 옵저버로 등록
`register(PHPhotoLibraryChangeObserver)`

**Comment by kjoonk** [comment]
작동됩니다. 사진을 추가하거나 제거하면 photoApp에 반영돼요.
관건은 `DispatchQueue.main.async`였어요.
`feature-photo-library`에 `merge`해 놓았어요. `pull`하시면 됩니다.
