### ISSUE TITLE
[step3] DoodleViewController 생성 및 화면 전환 

### ISSUE THREAD

**Issue by delmaSong** [codesquad-memeber-2020/photos-2#9]
- [x] NavigationBar 좌측에 +버튼을 추가한다.
- [x] +(add) 버튼을 누르면 Modal로 CollectionViewController에서 상속받은 새로운 DoodleViewController를 표시한다.
반드시 코드로 NavigationController를 embed 한 상태로 present 시킨다.

DoodleViewController 는 다음과 같이 설정하고 구현한다.
- [x] CollectionView 배경색을 어두운 회색으로 지정하고, Title을 명시한다.
- [x] Close 역할을 하는 Right-BarButton 을 ViewDidLoad() 에서 코드로 생성해서 설정한다.
- [x] Close버튼을 누르면 dismiss한다.
- [x] 셀 크기는 110 x 50 크기로 지정한다.
- [x] 셀에는 앞 단계와 마찬가지로 UIImageView를 추가하고 커스텀 셀 클래스를 만들어서 연결한다.
- [x] DataSource 프로토콜에서는 모델 객체에 개수와 indexPath에 맞는 데이터 객체를 받아와서 image항목에 있는 이미지를 셀에 표시한다.

**Comment by kjoonk** [comment]
작업 내용
- 스토리보드에서 ViewController를 추가하고 class를 DooleViewController로 지정
- add 버튼을 클릭: 
    - doodleController를 생성하고 navigationController에 Embed되도록 함.
    - doodleController를 표시(present)했지만 navigationBar가 보이지 않음 ❗️
    - navigationController를 표시하는 것으로 해결
- DoodleViewController.viewDidLoad()
    - 배경색, title 설정
    - 바에 close 버튼 추가하고 뷰를 닫도록(dismiss) 설정
    - selector 사용법을 알게 됐지만, 왜 클로저를 대신 사용하지 않는 지 궁금함 ❓
